version: '2'
services:
  web:
    image: tomcat
    ports:
    - "8080:8080"
    volumes:
    - ./target/Transfer.war:/usr/local/tomcat/webapps/ROOT.war
    - ./target/Transfer:/usr/local/tomcat/webapps/ROOT
